[package]
name = "proveno-noir"
version.workspace = true
edition.workspace = true

[dependencies]
proveno = { workspace = true }
proveno-zk = { path = "..", features = ["zkvm", "serde"] }
proveno-witness = { path = "../proveno-witness" }
serde_json.workspace = true


[[bin]]
name = "proveno-noir-witness"
path = "src/main.rs"
