[package]
name = "proveno-noir"
version.workspace = true
edition.workspace = true

[dependencies]
proveno = { path = "..", features = ["zkvm", "serde"] }
proveno-witness = { path = "../proveno-witness" }
serde_json.workspace = true

[dev-dependencies]
proveno = { path = "..", features = ["zkvm"] }

[[bin]]
name = "proveno-noir-witness"
path = "src/main.rs"
