[package]
name = "proveno-witness"
version.workspace = true
edition.workspace = true

[dependencies]
proveno = { path = "..", features = ["zkvm", "serde", "std"] }
serde.workspace = true
serde_json.workspace = true
reqwest = { workspace = true, features = ["blocking"] }

[[bin]]
name = "proveno-witness"
path = "src/main.rs"
