// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IOpenVmVerifier} from "./IOpenVmVerifier.sol";

/// @notice Interface of the Groth16Verifier.sol generated by `cargo openvm keygen --evm`.
/// Generated by gnark over BN254. One public signal: the BN254-field-reduced public inputs hash.
interface IGroth16Verifier {
    /// @param _pA        G1 proof point A (gnark encoding).
    /// @param _pB        G2 proof point B (gnark encoding).
    /// @param _pC        G1 proof point C (gnark encoding).
    /// @param _pubSignals Public signals: [0] = publicInputsHash mod BN254_FIELD_SIZE.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[1] calldata _pubSignals
    ) external view returns (bool);
}

/// @notice Adapts the OpenVM-generated Groth16Verifier to the IOpenVmVerifier interface.
///
/// Deployment workflow:
///   1. Run `cargo openvm keygen --evm` — generates EVM-compatible proving key.
///   2. Run `cargo openvm prove evm ...` — produces proof.json with Groth16 calldata.
///   3. OpenVM emits a matching Groth16Verifier.sol — deploy it on the target network.
///   4. Deploy this adapter, passing the Groth16Verifier address to the constructor.
///   5. Set OPENVM_VERIFIER_ADDR=<adapter address> when running the Deploy script.
///
/// publicInputsHash computation note:
///   LuaiVerifier computes: keccak256(abi.encode(b1, b2, b3, b4, b5, b6))
///   For six bytes32 values, abi.encode is plain concatenation (192 bytes), so this
///   equals keccak256(raw_public_values) — matching what OpenVM commits to via reveal_bytes32.
///   Groth16 public signals must be BN254 field elements (< 2^254 + some), so this adapter
///   reduces the 256-bit hash modulo the field order before forwarding to the verifier.
///   If OpenVM's generated verifier uses a different reduction (e.g. top-byte mask), the
///   Groth16Verifier.sol's expected input encoding takes precedence — inspect the generated
///   contract and update this adapter accordingly.
contract OpenVmGroth16Verifier is IOpenVmVerifier {
    /// @dev BN254 (alt_bn128) scalar field modulus.
    uint256 private constant BN254_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    IGroth16Verifier public immutable groth16Verifier;

    constructor(address _groth16Verifier) {
        groth16Verifier = IGroth16Verifier(_groth16Verifier);
    }

    /// @notice Verify an OpenVM EVM (Groth16) proof.
    /// @param proof            ABI-encoded Groth16 proof points:
    ///                         abi.encode(uint[2] pA, uint[2][2] pB, uint[2] pC).
    ///                         Produced by the luai packager from proof.json.
    /// @param publicInputsHash keccak256 of the six public input commitments (LuaiVerifier).
    function verify(bytes calldata proof, bytes32 publicInputsHash) external view override returns (bool) {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) =
            abi.decode(proof, (uint[2], uint[2][2], uint[2]));

        uint[1] memory pubSignals;
        pubSignals[0] = uint256(publicInputsHash) % BN254_FIELD_SIZE;

        return groth16Verifier.verifyProof(pA, pB, pC, pubSignals);
    }
}
